//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTE_EVENT_HIST
    {
        public int ID { get; set; }
        public int AGENT_CODE { get; set; }
        public int ACTE_REF_ARR { get; set; }
        public short ACTE_ANN_VISA { get; set; }
        public short ACTE_STADE { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public short CREATED_BY { get; set; }
    }
}
