//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_PARAM
    {
        public short SS_TYP_MVT { get; set; }
        public string A_COD_CATEG { get; set; }
        public string A_COD_CORPS { get; set; }
        public string A_COD_CADRE { get; set; }
        public string A_COD_GRADE { get; set; }
        public short A_COD_ELO { get; set; }
        public string N_COD_CATEG { get; set; }
        public string N_COD_CORPS { get; set; }
        public string N_COD_CADRE { get; set; }
        public string N_COD_GRADE { get; set; }
        public Nullable<short> N_COD_ELO { get; set; }
        public Nullable<short> DUREE_GRADE { get; set; }
        public Nullable<short> DUREE_CADRE { get; set; }
        public Nullable<short> DUREE_ADM { get; set; }
        public Nullable<short> DUREE_ELO { get; set; }
        public Nullable<short> DUREE_TITUL { get; set; }
    }
}
