//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;

    public partial class AGENT : AuditableEntity<long>
    {
        public int COD_AG { get; set; }
        public string COD_S_AF { get; set; }
        public string COD_POS { get; set; }
        public Nullable<short> COD_NIV { get; set; }
        public Nullable<short> COD_LOC { get; set; }
        public string COD_DEP { get; set; }
        public string COD_ART { get; set; }
        public string COD_SRV { get; set; }
        public string COD_NAT { get; set; }
        public string SIT_F_AG { get; set; }
        public string TYP_MVT { get; set; }
        public Nullable<short> SS_TYP_MVT { get; set; }
        public Nullable<short> COD_USR { get; set; }
        public string COD_PAYS { get; set; }
        public Nullable<int> NUM_PB { get; set; }
        public Nullable<System.DateTime> DAT_SIT_PB { get; set; }
        public string COD_S_AF_FTF { get; set; }
        public string COD_SRV_S_ANT { get; set; }
        public string NOM_AG { get; set; }
        public string PRENOM_AG { get; set; }
        public string NOM_ARAB_AG { get; set; }
        public string PRENOM_ARAB_AG { get; set; }
        public Nullable<System.DateTime> ANC_ADM { get; set; }
        public string CIN_A_AG { get; set; }
        public Nullable<int> CIN_N_AG { get; set; }
        public Nullable<short> JOU_N_AG { get; set; }
        public Nullable<short> MOI_N_AG { get; set; }
        public Nullable<short> ANN_N_AG { get; set; }
        public string SEX_AG { get; set; }
        public Nullable<System.DateTime> DAT_REC { get; set; }
        public Nullable<short> ETAPE { get; set; }
        public Nullable<short> LOT { get; set; }
        public string ADRESSE { get; set; }
        public Nullable<short> COD_ELO_REC { get; set; }
        public Nullable<System.DateTime> ANC_ELO_REC { get; set; }
        public Nullable<short> NOTE_AV { get; set; }
        public Nullable<System.DateTime> DAT_S_AF { get; set; }
        public Nullable<System.DateTime> DAT_POS { get; set; }
        public Nullable<System.DateTime> DAT_SS_TYP_MVT { get; set; }
        public Nullable<System.DateTime> DAT_S_AF_FTF { get; set; }
        public Nullable<short> COD_LIEU_NAISS { get; set; }
        public string ADRESSE_ARAB { get; set; }
        public string COD_S_ORD { get; set; }
    }
}
