//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT_DECORE
    {
        public string COD_DECO { get; set; }
        public int COD_AG { get; set; }
        public Nullable<System.DateTime> DATE_EFFET { get; set; }
    }
}
