//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        public int COD_AG { get; set; }
        public string COD_S_AF { get; set; }
        public string COD_POS { get; set; }
        public Nullable<byte> COD_NIV { get; set; }
        public Nullable<short> COD_LOC { get; set; }
        public string COD_DEP { get; set; }
        public string COD_ART { get; set; }
        public string COD_SRV { get; set; }
        public string COD_NAT { get; set; }
        public string SIT_F_AG { get; set; }
        public string TYP_MVT { get; set; }
        public Nullable<byte> SS_TYP_MVT { get; set; }
        public Nullable<short> COD_USR { get; set; }
        public string COD_PAYS { get; set; }
        public Nullable<int> NUM_PB { get; set; }
        public Nullable<System.DateTime> DAT_SIT_PB { get; set; }
        public string COD_S_AF_FTF { get; set; }
        public string COD_SRV_S_ANT { get; set; }
        public string NOM_AG { get; set; }
        public string PRENOM_AG { get; set; }
        public string NOM_ARAB_AG { get; set; }
        public string PRENOM_ARAB_AG { get; set; }
        public Nullable<System.DateTime> ANC_ADM { get; set; }
        public string CIN_A_AG { get; set; }
        public Nullable<int> CIN_N_AG { get; set; }
        public Nullable<byte> JOU_N_AG { get; set; }
        public Nullable<byte> MOI_N_AG { get; set; }
        public Nullable<short> ANN_N_AG { get; set; }
        public string SEX_AG { get; set; }
        public Nullable<System.DateTime> DAT_REC { get; set; }
        public Nullable<bool> ETAPE { get; set; }
        public Nullable<short> LOT { get; set; }
        public string ADRESSE { get; set; }
        public Nullable<byte> COD_ELO_REC { get; set; }
        public Nullable<System.DateTime> ANC_ELO_REC { get; set; }
        public Nullable<short> NOTE_AV { get; set; }
        public Nullable<System.DateTime> DAT_S_AF { get; set; }
        public Nullable<System.DateTime> DAT_POS { get; set; }
        public Nullable<System.DateTime> DAT_SS_TYP_MVT { get; set; }
        public Nullable<System.DateTime> DAT_S_AF_FTF { get; set; }
        public Nullable<short> COD_LIEU_NAISS { get; set; }
        public string ADRESSE_ARAB { get; set; }
        public string COD_S_ORD { get; set; }
    }
}
