//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMPS_DS_MVT
    {
        public byte COD_TABLE { get; set; }
        public short COD_CHAMPS { get; set; }
        public string LIB_CHAMPS { get; set; }
        public string TYP_CHAMPS { get; set; }
        public byte LONG_CHAMPS { get; set; }
    }
}
