//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDITION
    {
        public string CONDITION1 { get; set; }
        public byte ORDRE { get; set; }
        public string TYP_MVT { get; set; }
        public string EXPRESSION { get; set; }
    }
}
