//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGES
    {
        public int COD_AG { get; set; }
        public System.DateTime DATE_DEBUT_CONG { get; set; }
        public string COD_TYP_CONGE { get; set; }
        public Nullable<short> NBR_JOURS_CONG { get; set; }
        public string LIEU { get; set; }
        public Nullable<short> RELIQUAT { get; set; }
        public string LIEU_ARAB { get; set; }
    }
}
