//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONJOINT_ORD
    {
        public int COD_AG { get; set; }
        public int NUM_CONJ { get; set; }
        public string SIT_CONJ { get; set; }
        public string PRF_CONJ { get; set; }
        public string NAT_CONJ { get; set; }
        public string NOM_PR_CONJ { get; set; }
        public Nullable<int> DOTI_CONJ { get; set; }
        public string CIN_A_CONJ { get; set; }
        public Nullable<int> CIN_N_CONJ { get; set; }
        public Nullable<System.DateTime> DAT_SIT_CONJ { get; set; }
    }
}
