//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUT_FORMATION
    {
        public int NUM_SESSION { get; set; }
        public int COD_AG { get; set; }
        public Nullable<short> F_ENCADRE { get; set; }
        public Nullable<short> F_TRANSPORT { get; set; }
        public Nullable<short> F_SUPPORT { get; set; }
        public Nullable<short> F_MAT_DIDA { get; set; }
        public Nullable<short> INDEM_DEPL { get; set; }
    }
}
