//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRITERES_CAP
    {
        public int NUMCRITERE { get; set; }
        public Nullable<short> COD_LOC { get; set; }
        public string COD_DEP { get; set; }
        public string COD_ART { get; set; }
        public string COD_SRV { get; set; }
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public Nullable<int> NUMCAP { get; set; }
        public string COD_S_AF_FTF { get; set; }
    }
}
