//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIPLOMES_DS
    {
        public int COD_AG { get; set; }
        public string COD_PAYS { get; set; }
        public string COD_DIP { get; set; }
        public System.DateTime DAT_OBT_DIPL { get; set; }
        public Nullable<int> REF_ARRETE { get; set; }
        public Nullable<short> ANN_VISA { get; set; }
        public Nullable<short> COD_SPEC { get; set; }
    }
}
