//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENF_PAC_DS
    {
        public int COD_AG { get; set; }
        public Nullable<int> NUM_CONJ { get; set; }
        public short NUM_PAC { get; set; }
        public string PRF_GARDE { get; set; }
        public string SIT_PAC { get; set; }
        public string COD_GARDE { get; set; }
        public string LIEN_PAR { get; set; }
        public Nullable<System.DateTime> DAT_N_PAC { get; set; }
        public string NOM_PAC { get; set; }
        public string PRENOM_PAC { get; set; }
        public Nullable<short> ANN_SCOL1 { get; set; }
        public Nullable<short> ANN_SCOL2 { get; set; }
        public string NOM_PR_GARDE { get; set; }
        public string CIN_A_GARDE { get; set; }
        public Nullable<int> CIN_N_GARDE { get; set; }
        public Nullable<int> DOTI_GARDE { get; set; }
        public Nullable<System.DateTime> DAT_SIT_PAC { get; set; }
        public Nullable<int> CON_COD_AG { get; set; }
    }
}
