//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETAT_ENGAGEMENT
    {
        public string CODIMPST { get; set; }
        public int COD_AG { get; set; }
        public string NUMECOLO { get; set; }
        public string CODESERV { get; set; }
        public string CODELOCA { get; set; }
        public string CODEPOST { get; set; }
        public string NOM_PREN { get; set; }
        public string SEXEAGEN { get; set; }
        public string CODEPAYS { get; set; }
        public string CODSERVD { get; set; }
        public Nullable<System.DateTime> DATDEBSI { get; set; }
        public System.DateTime DATFINSI { get; set; }
        public string CODSITST { get; set; }
        public string CODEZONE { get; set; }
        public Nullable<short> POININDI { get; set; }
        public string CDTYPREP { get; set; }
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public string CODAVANC { get; set; }
        public Nullable<short> DEDUCTIO { get; set; }
        public string SIT_F_AG { get; set; }
        public Nullable<short> NOMBENFA { get; set; }
        public Nullable<short> DUREJOUR { get; set; }
        public Nullable<decimal> SALBRU_N { get; set; }
        public Nullable<decimal> SALBRU_A { get; set; }
        public Nullable<decimal> DIFFBRUT { get; set; }
        public Nullable<decimal> SALNET_N { get; set; }
        public Nullable<decimal> SALNET_A { get; set; }
        public Nullable<decimal> DIFF_NET { get; set; }
        public string CODEMUTA { get; set; }
        public Nullable<decimal> BASEIMPO { get; set; }
        public Nullable<decimal> SAISISS_ { get; set; }
        public Nullable<decimal> MONTRAPP { get; set; }
        public Nullable<int> NUMORDRE { get; set; }
        public System.DateTime DATE_EFF { get; set; }
    }
}
