//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVT_CARRIER_CONFIGURATION
    {
        public string NAME { get; set; }
        public string AREA_CODE { get; set; }
        public string PHONE { get; set; }
        public Nullable<decimal> PAGER_TYPE { get; set; }
        public Nullable<decimal> PROTOCOL { get; set; }
        public Nullable<decimal> CONNECT_DELAY { get; set; }
        public Nullable<decimal> TIMEOUT_PERIOD { get; set; }
        public Nullable<decimal> COUNTRY_ID { get; set; }
    }
}
