//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTRACT_CHAMPS_PLUS
    {
        public int COD_TITRE { get; set; }
        public int COD_AG { get; set; }
        public string LIB_LOT { get; set; }
        public string LIB_NOTE_AV { get; set; }
        public string LIB_GRADE_ASS { get; set; }
        public string LIB_LOT_A { get; set; }
        public string LIB_NOTE_AV_A { get; set; }
        public string LIB_GRADE_ASS_A { get; set; }
    }
}
