//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GipeOrdContext : DbContext
    {
        public GipeOrdContext()
            : base("name=GipeOrdContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGENT> AGENT { get; set; }
        public DbSet<TAB_SRV> TAB_SRV { get; set; }
        public DbSet<MVT_SIT_ADM> MVT_SIT_ADM { get; set; }
        public DbSet<TAB_LOC> TAB_LOC { get; set; }
        public DbSet<TAB_TYP_MVT> TAB_TYP_MVT { get; set; }
        public DbSet<TAB_GRADE> TAB_GRADE { get; set; }
        public DbSet<TAB_SS_TYP_MVT> TAB_SS_TYP_MVT { get; set; }
        public DbSet<SIT_ADM> SIT_ADM { get; set; }
    }
}
