//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDEM_AG
    {
        public short COD_IND { get; set; }
        public int COD_AG { get; set; }
        public Nullable<int> REF_ARRETE { get; set; }
        public Nullable<byte> ANN_VISA { get; set; }
        public Nullable<System.DateTime> DAT_ATTRIB { get; set; }
        public Nullable<System.DateTime> DAT_FIN { get; set; }
    }
}
