//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class INHIBER_CTL_POSTES_ACTE
    {
        public int REF_ARRETE { get; set; }
        public short ANN_VISA { get; set; }
        public Nullable<short> CONTROLE_POSTE { get; set; }
        public Nullable<short> CONTROLE_AGENT { get; set; }
    }
}
