//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class INHIBER_CTL_POSTES
    {
        public string TYP_MVT { get; set; }
        public short ORDRE { get; set; }
        public Nullable<short> SS_TYP_MVT { get; set; }
        public Nullable<short> COMPATIBILITE_GRADE { get; set; }
        public Nullable<short> COMPATIBILITE_ENTITE { get; set; }
        public string COD_POS { get; set; }
        public string COD_S_ST { get; set; }
    }
}
