//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class INIT_CHAMPS
    {
        public string TYP_MVT { get; set; }
        public short COD_TABLE { get; set; }
        public short COD_CHAMPS { get; set; }
        public short ORDRE { get; set; }
        public Nullable<short> SS_TYP_MVT { get; set; }
        public string EXPRESSION { get; set; }
        public string LISTE_CONDITIONS { get; set; }
        public Nullable<short> RESET { get; set; }
        public Nullable<short> MAJDS { get; set; }
    }
}
