//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_SERV
    {
        public int COD_AG { get; set; }
        public System.DateTime DAT_DEB { get; set; }
        public string TYP_INT { get; set; }
        public Nullable<short> SS_TYP_INT { get; set; }
        public Nullable<System.DateTime> DAT_FIN { get; set; }
    }
}
