//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUVEMENTS_CONSID
    {
        public int NUM_CONSID { get; set; }
        public string TYP_MVT { get; set; }
        public Nullable<short> SS_TYP_MVT { get; set; }
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public string COD_S_ST { get; set; }
        public Nullable<short> COD_FCT { get; set; }
        public string AUTRE_CRITERE { get; set; }
        public string CHAMPS_AUTRE_CRITERE { get; set; }
        public short COD_CONSID { get; set; }
    }
}
