//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;

    public partial class MVT_SIT_ADM : AuditableEntity<long>
    {
        public int M_NUM_ID { get; set; }
        public string M_TYP_MVT { get; set; }
        public Nullable<short> M_SS_TYP_MVT { get; set; }
        public Nullable<System.DateTime> M_DAT_EFF_MVT { get; set; }
        public Nullable<int> M_REF_ARRETE { get; set; }
        public Nullable<short> M_ANN_VISA { get; set; }
        public Nullable<int> M_COD_AG { get; set; }
        public string M_REP_SAL { get; set; }
        public Nullable<short> M_COD_USR { get; set; }
        public string AGT_COD_S_AF { get; set; }
        public string AGT_COD_POS { get; set; }
        public Nullable<short> AGT_COD_NIV { get; set; }
        public Nullable<short> AGT_COD_LOC { get; set; }
        public string AGT_COD_DEP { get; set; }
        public string AGT_COD_ART { get; set; }
        public string AGT_COD_SRV { get; set; }
        public string AGT_COD_NAT { get; set; }
        public string AGT_SIT_F_AG { get; set; }
        public string AGT_TYP_MVT { get; set; }
        public Nullable<short> AGT_SS_TYP_MVT { get; set; }
        public string AGT_COD_PAYS { get; set; }
        public Nullable<int> AGT_NUM_PB { get; set; }
        public string AGT_COD_S_AF_FTF { get; set; }
        public string AGT_COD_SRV_S_ANT { get; set; }
        public string AGT_NOM_AG { get; set; }
        public string AGT_PRENOM_AG { get; set; }
        public string AGT_NOM_ARAB_AG { get; set; }
        public string AGT_PRENOM_ARAB_AG { get; set; }
        public Nullable<System.DateTime> AGT_ANC_ADM { get; set; }
        public string AGT_CIN_A_AG { get; set; }
        public Nullable<int> AGT_CIN_N_AG { get; set; }
        public Nullable<short> AGT_JOU_N_AG { get; set; }
        public Nullable<short> AGT_MOI_N_AG { get; set; }
        public Nullable<short> AGT_ANN_N_AG { get; set; }
        public string AGT_SEX_AG { get; set; }
        public Nullable<System.DateTime> AGT_DAT_REC { get; set; }
        public Nullable<System.DateTime> AGT_DAT_S_AF { get; set; }
        public Nullable<System.DateTime> AGT_DAT_POS { get; set; }
        public Nullable<System.DateTime> AGT_DAT_SS_TYP_MVT { get; set; }
        public Nullable<System.DateTime> AGT_DAT_S_AF_FTF { get; set; }
        public string AGT_ADRESSE { get; set; }
        public Nullable<short> AGT_COD_ELO_REC { get; set; }
        public Nullable<System.DateTime> AGT_ANC_ELO_REC { get; set; }
        public Nullable<short> AGT_NOTE_AV { get; set; }
        public string AGT_ADRESSE_ARAB { get; set; }
        public string ADM_COD_CATEG { get; set; }
        public string ADM_COD_CORPS { get; set; }
        public string ADM_COD_CADRE { get; set; }
        public string ADM_COD_GRADE { get; set; }
        public Nullable<short> ADM_COD_ELO { get; set; }
        public Nullable<short> ADM_COD_FCT { get; set; }
        public string ADM_COD_S_ST { get; set; }
        public Nullable<short> ADM_COD_ORG_DET { get; set; }
        public Nullable<short> ADM_MOD_AV_GRADE { get; set; }
        public Nullable<short> ADM_COD_ECH { get; set; }
        public Nullable<System.DateTime> ADM_DAT_FIN_C { get; set; }
        public Nullable<short> ADM_TAUX_PRIME { get; set; }
        public Nullable<short> ADM_SPECIALITE { get; set; }
        public Nullable<System.DateTime> ADM_DAT_EFF_GR { get; set; }
        public Nullable<System.DateTime> ADM_ANC_GRADE { get; set; }
        public Nullable<System.DateTime> ADM_DAT_EFF_ELO { get; set; }
        public Nullable<System.DateTime> ADM_ANC_ELO { get; set; }
        public Nullable<System.DateTime> ADM_DAT_FCT { get; set; }
        public Nullable<System.DateTime> ADM_DAT_S_ST { get; set; }
        public Nullable<System.DateTime> ADM_ANC_CADRE { get; set; }
        public string ADM_COD_CATEG_ASS { get; set; }
        public string ADM_COD_CORPS_ASS { get; set; }
        public string ADM_COD_CADRE_ASS { get; set; }
        public string ADM_COD_GRADE_ASS { get; set; }
        public Nullable<System.DateTime> INT_DAT_DEB { get; set; }
        public string INT_TYP_INT { get; set; }
        public Nullable<short> INT_SS_TYP_INT { get; set; }
        public Nullable<System.DateTime> INT_DAT_FIN { get; set; }
        public Nullable<System.DateTime> ANT_DAT_DEB { get; set; }
        public string ANT_COD_SRV_S_ANT { get; set; }
        public string ANT_COD_CATEG { get; set; }
        public string ANT_COD_CORPS { get; set; }
        public string ANT_COD_CADRE { get; set; }
        public string ANT_COD_GRADE { get; set; }
        public Nullable<System.DateTime> ANT_DAT_FIN { get; set; }
        public string ANT_TYP_DEP_S_ANT { get; set; }
        public Nullable<int> CNJ_NUM_CONJ { get; set; }
        public string CNJ_SIT_CONJ { get; set; }
        public string CNJ_PRF_CONJ { get; set; }
        public string CNJ_NAT_CONJ { get; set; }
        public string CNJ_NOM_PR_CONJ { get; set; }
        public Nullable<int> CNJ_DOTI_CONJ { get; set; }
        public string CNJ_CIN_A_CONJ { get; set; }
        public Nullable<int> CNJ_CIN_N_CONJ { get; set; }
        public Nullable<System.DateTime> CNJ_DAT_SIT_CONJ { get; set; }
        public Nullable<short> ENF_NUM_PAC { get; set; }
        public Nullable<int> ENF_NUM_CONJ { get; set; }
        public string ENF_PRF_GARDE { get; set; }
        public string ENF_SIT_PAC { get; set; }
        public string ENF_COD_GARDE { get; set; }
        public string ENF_LIEN_PAR { get; set; }
        public Nullable<System.DateTime> ENF_DAT_N_PAC { get; set; }
        public string ENF_NOM_PAC { get; set; }
        public string ENF_PRENOM_PAC { get; set; }
        public Nullable<short> ENF_ANN_SCOL1 { get; set; }
        public Nullable<short> ENF_ANN_SCOL2 { get; set; }
        public string ENF_NOM_PR_GARDE { get; set; }
        public string ENF_CIN_A_GARDE { get; set; }
        public Nullable<int> ENF_CIN_N_GARDE { get; set; }
        public Nullable<int> ENF_DOTI_GARDE { get; set; }
        public Nullable<System.DateTime> ENF_DAT_SIT_PAC { get; set; }
        public string DIPL_COD_PAYS { get; set; }
        public string DIPL_COD_DIP { get; set; }
        public Nullable<System.DateTime> DIPL_DAT_OBT_DIPL { get; set; }
        public Nullable<int> DIPL_REF_ARRETE { get; set; }
        public Nullable<short> DIPL_ANN_VISA { get; set; }
        public Nullable<short> M_INDICE_REC { get; set; }
        public Nullable<short> M_INDICE { get; set; }
        public Nullable<int> M_INDEMNITE { get; set; }
        public Nullable<decimal> M_IMP_BUDG { get; set; }
        public string M_ZONE_SUD { get; set; }
        public string M_PHASE_MVT { get; set; }
        public Nullable<int> M_SALAIRE { get; set; }
        public string M_DECISION { get; set; }
        public Nullable<int> M_ORDRE_MVT { get; set; }
        public string M_OBSERV { get; set; }
        public string M_REMB_SAL { get; set; }
        public string M_DEP_GARDE { get; set; }
        public string M_DEP_CONJ { get; set; }
        public Nullable<int> M_NUM_ORD { get; set; }
        public Nullable<int> M_NUM_MENTION { get; set; }
        public Nullable<int> M_REF_ARRETE_AN { get; set; }
        public Nullable<short> M_ANN_VISA_AN { get; set; }
        public string M_CONDITION { get; set; }
        public Nullable<System.DateTime> M_DAT_LIB_PB { get; set; }
        public string M_LIB_ORG_DET { get; set; }
        public Nullable<decimal> M_IMP_BUD_ACCEUIL { get; set; }
        public Nullable<short> M_COD_SPC { get; set; }
        public Nullable<int> IND_REF_ARRETE { get; set; }
        public Nullable<short> IND_ANN_VISA { get; set; }
        public Nullable<System.DateTime> IND_DAT_ATTRIB { get; set; }
        public Nullable<System.DateTime> IND_DAT_FIN { get; set; }
        public Nullable<int> IND_COD_AG { get; set; }
        public Nullable<short> IND_COD_IND { get; set; }
        public Nullable<short> DIPL_COD_SPEC { get; set; }
        public string AGT_COD_S_ORD { get; set; }
        public Nullable<short> AGT_LOT { get; set; }
        public Nullable<short> AGT_ETAPE { get; set; }
        public Nullable<short> AGT_COD_LIEU_NAISS { get; set; }
    }
}
