//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLD_DTRSR_UTILISATEURS
    {
        public short OLD_COD_USR { get; set; }
        public Nullable<short> NEW_COD_USR { get; set; }
        public string LIB_USR { get; set; }
        public Nullable<System.DateTime> DAT_CREAT_NEW_USER { get; set; }
        public string OLD_MOT_DE_PASSE { get; set; }
        public string OLD_COD_S_ORD { get; set; }
        public string NEW_COD_S_ORD { get; set; }
        public string OLD_DIRECTION { get; set; }
    }
}
