//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIE
    {
        public string CODIMPST { get; set; }
        public string CODESERV { get; set; }
        public int COD_AG { get; set; }
        public string NOM_PREN { get; set; }
        public Nullable<decimal> SALA_NET { get; set; }
        public Nullable<decimal> MONTRAPP { get; set; }
        public Nullable<decimal> RAPPBRUT { get; set; }
        public Nullable<decimal> SAISISS_ { get; set; }
        public string CODMODRE { get; set; }
        public string REFMODRE { get; set; }
        public string CODEBANQ { get; set; }
        public System.DateTime DATE_EFF { get; set; }
    }
}
