//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_FORMATION_CONTINUE
    {
        public short NUM_PLAN { get; set; }
        public Nullable<System.DateTime> DATE_DEBUT_PLAN { get; set; }
        public Nullable<System.DateTime> DATE_FIN_PLAN { get; set; }
    }
}
