//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREP_ERRATUM
    {
        public int NUM_ORD { get; set; }
        public string COD_CATEG1 { get; set; }
        public string COD_CORPS1 { get; set; }
        public string COD_CADRE1 { get; set; }
        public string COD_GRADE1 { get; set; }
        public string COD_CATEG2 { get; set; }
        public string COD_CORPS2 { get; set; }
        public string COD_CADRE2 { get; set; }
        public string COD_GRADE2 { get; set; }
        public string COD_DEP1 { get; set; }
        public string COD_ART1 { get; set; }
        public string COD_SRV1 { get; set; }
        public string COD_DEP2 { get; set; }
        public string COD_ART2 { get; set; }
        public string COD_SRV2 { get; set; }
        public string ANNEE_LOI { get; set; }
        public string NUM_LOI { get; set; }
        public string TYP_MENTION { get; set; }
        public Nullable<int> NUM_MENTION { get; set; }
        public string ORIGINE { get; set; }
        public string OBSERV { get; set; }
    }
}
