//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREP_EFFECTIF_MENT
    {
        public int NUM_ORD { get; set; }
        public System.DateTime DAT_EFF { get; set; }
        public Nullable<System.DateTime> DAT_FIN { get; set; }
        public Nullable<int> EFFECTIF_BUD { get; set; }
        public Nullable<int> EFFECTIF_REG { get; set; }
        public Nullable<int> EFFECTIF_ORD { get; set; }
        public Nullable<int> EFFECTIF_UTILISE { get; set; }
        public Nullable<int> EFFECTIF_VALIDE { get; set; }
    }
}
