//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREP_ERRATUM_INFO
    {
        public int NUM_ORD { get; set; }
        public string TEXT_ERRT { get; set; }
        public Nullable<System.DateTime> DAT_VISA_BUDG { get; set; }
    }
}
