//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRIQUES_PAIE
    {
        public int COD_AG { get; set; }
        public string CODERUBR { get; set; }
        public Nullable<decimal> NET_MAND { get; set; }
        public Nullable<decimal> RAPPMAND { get; set; }
        public string NUMEDOSS { get; set; }
        public Nullable<decimal> MTOTPREC { get; set; }
        public Nullable<decimal> RESTPAYE { get; set; }
        public System.DateTime DATE_EFF { get; set; }
        public string CODIMPST { get; set; }
    }
}
