//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRIQUES_ETAT_ENGAGEMENT
    {
        public int COD_AG { get; set; }
        public string CODERUBR { get; set; }
        public Nullable<decimal> MONTRUBR { get; set; }
        public Nullable<decimal> MONTRUBA { get; set; }
        public Nullable<decimal> DIFFRUBR { get; set; }
        public string NUMECOLO { get; set; }
        public System.DateTime DATFINSI { get; set; }
        public System.DateTime DATE_EFF { get; set; }
        public string CODIMPST { get; set; }
    }
}
