//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_ANT
    {
        public int COD_AG { get; set; }
        public System.DateTime DAT_DEB { get; set; }
        public string COD_SRV_S_ANT { get; set; }
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public Nullable<System.DateTime> DAT_FIN { get; set; }
        public string TYP_DEP_S_ANT { get; set; }
        public Nullable<int> REF_ARRETE { get; set; }
        public Nullable<byte> ANN_VISA { get; set; }
        public string DECISION { get; set; }
    }
}
