//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION_EVALUE
    {
        public int NUM_SESSION { get; set; }
        public int COD_AG { get; set; }
        public Nullable<short> DUREE_SESSION { get; set; }
        public Nullable<short> CONTENU { get; set; }
        public Nullable<short> SUPPORT_COURS { get; set; }
        public Nullable<short> ANIMATEUR { get; set; }
        public Nullable<short> SALLE { get; set; }
    }
}
