//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION_FORMATION
    {
        public int NUM_SESSION { get; set; }
        public string COD_LANGUE { get; set; }
        public string COD_PAYS { get; set; }
        public string COD_ORG { get; set; }
        public string COD_TYPE_FORMA { get; set; }
        public Nullable<short> NUM_PLAN { get; set; }
        public Nullable<System.DateTime> DATE_SESSION { get; set; }
        public Nullable<byte> NBR_JOURS_FORM { get; set; }
        public string REALISE { get; set; }
        public Nullable<byte> EFFE_PREV { get; set; }
        public string LIEU { get; set; }
        public string LIEU_ARAB { get; set; }
        public string OBJET_TITRE { get; set; }
        public string OBJET_TITRE_ARAB { get; set; }
    }
}
