//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIT_ADM_ORD
    {
        public int COD_AG { get; set; }
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public Nullable<short> COD_ELO { get; set; }
        public Nullable<short> COD_FCT { get; set; }
        public string COD_S_ST { get; set; }
        public Nullable<short> COD_ORG_DET { get; set; }
        public Nullable<short> MOD_AV_GRADE { get; set; }
        public Nullable<short> COD_ECH { get; set; }
        public Nullable<System.DateTime> DAT_FIN_C { get; set; }
        public Nullable<short> TAUX_PRIME { get; set; }
        public Nullable<short> SPECIALITE { get; set; }
        public Nullable<System.DateTime> DAT_EFF_GR { get; set; }
        public Nullable<System.DateTime> ANC_GRADE { get; set; }
        public Nullable<System.DateTime> DAT_EFF_ELO { get; set; }
        public Nullable<System.DateTime> ANC_ELO { get; set; }
        public Nullable<System.DateTime> DAT_FCT { get; set; }
        public Nullable<System.DateTime> DAT_S_ST { get; set; }
        public string COD_CATEG_ASS { get; set; }
        public string COD_CORPS_ASS { get; set; }
        public string COD_CADRE_ASS { get; set; }
        public string COD_GRADE_ASS { get; set; }
        public Nullable<System.DateTime> ANC_CADRE { get; set; }
    }
}
