//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIT_PB_DS
    {
        public int NUM_PB { get; set; }
        public System.DateTime DAT_SIT_PB { get; set; }
        public Nullable<int> NUM_ORD { get; set; }
        public string SIT_PB { get; set; }
        public string COD_INT { get; set; }
        public Nullable<int> DOTI_INT { get; set; }
        public Nullable<System.DateTime> DAT_PREOC { get; set; }
        public Nullable<System.DateTime> DAT_PRELIB { get; set; }
        public string MENTION { get; set; }
        public Nullable<int> REFARRETE_O { get; set; }
        public Nullable<short> ANNVISA_O { get; set; }
        public Nullable<int> REFARRETE_L { get; set; }
        public Nullable<short> ANNVISA_L { get; set; }
        public Nullable<short> TYP_BLOC { get; set; }
        public Nullable<short> TYP_LIB { get; set; }
        public Nullable<short> NB_OCC { get; set; }
    }
}
