//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMDEFAUTH_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public string DEFAUTH_CONSOLEUSER_ { get; set; }
        public string DEFAUTH_OSUSERNAME_ { get; set; }
        public Nullable<int> DEFAUTH_ISOSUSERNAMESET_ { get; set; }
        public string DEFAUTH_OSPASSWORD_ { get; set; }
        public Nullable<int> DEFAUTH_ISOSPASSWORDSET_ { get; set; }
        public string DEFAUTH_DBUSERNAME_ { get; set; }
        public Nullable<int> DEFAUTH_ISDBUSERNAMESET_ { get; set; }
        public string DEFAUTH_DBPASSWORD_ { get; set; }
        public Nullable<int> DEFAUTH_ISDBPASSWORDSET_ { get; set; }
        public string DEFAUTH_INTERNALPASSWORD_ { get; set; }
        public Nullable<int> DEFAUTH_ISINTERNALPASSWORDSET_ { get; set; }
    }
}
