//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMDEPENDENTLINKS
    {
        public int DEPENDENTID { get; set; }
        public int DEPENDENTTYPE { get; set; }
        public int DEPENDEEID { get; set; }
        public int DEPENDEETYPE { get; set; }
        public int ASSOCIATION_ID_ { get; set; }
    }
}
