//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMFORMALPARAMETER_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public string FORMALPARAMETER_PARAMETERNAME_ { get; set; }
        public string FORMALPARAMETER_DESCRIPTION_ { get; set; }
        public Nullable<int> FORMALPARAMETER_ISSCALAR_ { get; set; }
        public Nullable<int> FORMALPARAMETER_ISMANDATORY_ { get; set; }
        public Nullable<int> FORMALPARAMETER_USERDEFFLAG_ { get; set; }
        public Nullable<int> NUMBERFORMALPARAMETER_LBOUND_ { get; set; }
        public Nullable<int> NUMBERFORMALPARAMETER_UBOUND_ { get; set; }
        public Nullable<int> OBJECTFORMALPARAMETER_FPOT_ { get; set; }
    }
}
