//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMFOLDER_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public string FOLDER_FOLDERNAME_ { get; set; }
        public string FOLDER_DESCRIPTION_ { get; set; }
        public Nullable<System.DateTime> FOLDER_LASTUPDATE_ { get; set; }
        public Nullable<int> FOLDER_USERDATA1_ { get; set; }
        public Nullable<int> FOLDER_USERDATA2_ { get; set; }
    }
}
