//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMHOST_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public string HOST_HOSTNAME_ { get; set; }
        public string HOST_RPCADDRESS_ { get; set; }
        public string HOST_FTPADDRESS_ { get; set; }
        public string HOST_OS_ { get; set; }
        public string HOST_OSVERSION_ { get; set; }
        public Nullable<int> HOST_STATE_ { get; set; }
        public Nullable<int> HOST_ISSOSERVER_ { get; set; }
        public Nullable<int> HOST_ISDISTRIBUTIONHOST_ { get; set; }
    }
}
