//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMLOGMESSAGE_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public Nullable<System.DateTime> LOGMESSAGE_TIME_ { get; set; }
        public string LOGMESSAGE_PROGRAMCOUNTER_ { get; set; }
        public string LOGMESSAGE_MESSAGE_ { get; set; }
        public Nullable<int> LOGMESSAGE_KIND_ { get; set; }
        public Nullable<int> LOGMESSAGE_PRIORITY_ { get; set; }
    }
}
