//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMMONTHLYENTRY_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public Nullable<int> MONTHLYENTRY_DAY_ { get; set; }
        public Nullable<int> MONTHLYENTRY_TOFDAY_SPM_ { get; set; }
        public Nullable<int> MONTHLYENTRY_TOFDAY_ZONE_ { get; set; }
    }
}
