//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMMOWNERLINKS
    {
        public int MOWNERID { get; set; }
        public int MOWNERTYPE { get; set; }
        public int MOWNEEID { get; set; }
        public int MOWNEETYPE { get; set; }
        public int ASSOCIATION_ID_ { get; set; }
        public string ASSOCIATION_REMARKS_ { get; set; }
    }
}
