//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_AD_NODES_
    {
        public string OWNER { get; set; }
        public string NODE { get; set; }
        public string REMOTE_NAME { get; set; }
        public Nullable<bool> SELECTED_FOR_DISCOVERY { get; set; }
        public string DISCOVER_STATE { get; set; }
        public Nullable<bool> DISCOVER_FLAGS { get; set; }
        public Nullable<System.DateTime> DISCOVER_TIME { get; set; }
        public Nullable<System.DateTime> LAST_CONTACT_ATTEMPT { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
    }
}
