//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_JOB_
    {
        public decimal ID { get; set; }
        public string OWNER { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string SERVICE_ID { get; set; }
        public string SCHEDULE { get; set; }
        public string MACHINE_NAME { get; set; }
        public Nullable<decimal> READONLY { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public Nullable<decimal> FIXEDIT { get; set; }
        public Nullable<decimal> LIBRARY { get; set; }
        public string JOB_TMPSCRIPTFILE { get; set; }
    }
}
