//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_AD_PARMS_
    {
        public string OWNER { get; set; }
        public decimal BACKGROUND_DISCOVERY { get; set; }
        public int BACKGROUND_FREQUENCY { get; set; }
    }
}
