//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_AUTO_DISCOVERY_PARMS_
    {
        public string OWNER { get; set; }
        public decimal AD_FREQUENCY { get; set; }
        public decimal AD_CONN_TIMEOUT { get; set; }
        public decimal AD_UPDATE_FREQUENCY { get; set; }
        public decimal AD_UPDATE_COUNT { get; set; }
        public Nullable<short> AD_ENABLE { get; set; }
    }
}
