//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_BLOB_
    {
        public string OWNER { get; set; }
        public string ID { get; set; }
        public string SUBID { get; set; }
        public Nullable<decimal> LEN { get; set; }
        public byte[] DATA { get; set; }
    }
}
