//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_AUTO_DISCOVERY_ITEM_
    {
        public string OWNER { get; set; }
        public decimal IPADDR_BYTE1 { get; set; }
        public decimal IPADDR_BYTE2 { get; set; }
        public decimal IPADDR_BYTE3 { get; set; }
        public Nullable<decimal> IPADDR_BYTE4 { get; set; }
        public decimal IPADDR_BYTE4_UPPERLIMIT { get; set; }
        public decimal IPADDR_BYTE4_LASTUSED { get; set; }
    }
}
