//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_SERVICE_GROUP_ITEM_
    {
        public string OWNER { get; set; }
        public string GROUP_NAME { get; set; }
        public string OBJECT_NAME { get; set; }
        public decimal OBJECT_TYPE { get; set; }
        public string ISAGROUP { get; set; }
    }
}
