//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPRODUCT_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public Nullable<int> PRODUCT_OWNERID_ { get; set; }
        public Nullable<int> PRODUCT_OWNERTYPE_ { get; set; }
        public Nullable<int> PRODUCT_PRODUCTID_ { get; set; }
        public string PRODUCT_DEPENDENCIES_ { get; set; }
        public string PRODUCT_SHARABLE_ { get; set; }
        public string PRODUCT_SELECTED_ { get; set; }
        public string PRODUCT_PRDFILE_ { get; set; }
    }
}
