//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPRODUCTATTRIBUTE_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public string PRODUCTATTRIBUTE_PRODUCTNAME_ { get; set; }
        public string PRODUCTATTRIBUTE_ITFCLABEL_ { get; set; }
        public string PRODUCTATTRIBUTE_VERSION_ { get; set; }
        public string PRODUCTATTRIBUTE_OS_ { get; set; }
        public Nullable<int> PRODUCTATTRIBUTE_PRODUCTSIZE_ { get; set; }
        public string PRODUCTATTRIBUTE_PRDPATH_ { get; set; }
        public string PRODUCTATTRIBUTE_PARENT_ { get; set; }
        public string PRODUCTATTRIBUTE_VISIBLE_ { get; set; }
        public string PRODUCTATTRIBUTE_OPEN_ { get; set; }
        public string PRODUCTATTRIBUTE_DESCR_ { get; set; }
    }
}
