//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMRELEASE_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public Nullable<int> RELEASE_STATE_ { get; set; }
        public Nullable<int> RELEASE_MEDIATYPE_ { get; set; }
        public Nullable<int> RELEASE_PRODFILETYPE_ { get; set; }
        public string RELEASE_LOCATION_ { get; set; }
        public string RELEASE_DESCRIPTION_ { get; set; }
        public string RELEASE_PARTNUMBER_ { get; set; }
        public string RELEASE_THIRDPARTYRELEASEPRAM_ { get; set; }
        public string RELEASE_USERREMARK_ { get; set; }
    }
}
