//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMRUN_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public Nullable<int> RUN_STATE_ { get; set; }
        public Nullable<System.DateTime> RUN_STARTTIME_ { get; set; }
        public Nullable<System.DateTime> RUN_ENDTIME_ { get; set; }
        public string RUN_PROGRAMCOUNTER_ { get; set; }
        public Nullable<int> RUN_FINISHSTATE_ { get; set; }
    }
}
