//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSCHEDULE_S
    {
        public int NAMEDOBJECT_ID_SEQUENCEID_ { get; set; }
        public Nullable<int> NAMEDOBJECT_ID_OBJECTTYPE_ { get; set; }
        public Nullable<int> SCHEDULE_HASEXPIRATION_ { get; set; }
        public Nullable<System.DateTime> SCHEDULE_EXP_DATE_ { get; set; }
        public Nullable<int> SCHEDULE_EXP_TOD_SPM_ { get; set; }
        public Nullable<int> SCHEDULE_EXP_TOD_ZONE_ { get; set; }
        public Nullable<int> REPEATED_ISIMMEDIATE_ { get; set; }
        public Nullable<System.DateTime> REPEATED_STARTTIME_DATE_ { get; set; }
        public Nullable<int> REPEATED_STARTTIME_TOD_SPM_ { get; set; }
        public Nullable<int> REPEATED_STARTTIME_TOD_ZONE_ { get; set; }
        public Nullable<int> REPEATED_SECONDSINPERIOD_ { get; set; }
    }
}
