//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;

    public partial class TAB_SS_TYP_MVT : AuditableEntity<long>
    {
        public string TYP_MVT { get; set; }
        public short SS_TYP_MVT { get; set; }
        public string COD_POS { get; set; }
        public string LIB_SS_TYP_MVT { get; set; }
        public string LIB_ABREGE { get; set; }
        public Nullable<short> TYP_INT { get; set; }
        public Nullable<short> TYP_POS { get; set; }
        public string LIB_SS_TYP_MVT_A { get; set; }
    }
}
