//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_E_E_I_D_OLD
    {
        public byte COD_ECH { get; set; }
        public byte COD_ELO { get; set; }
        public Nullable<short> INDICE { get; set; }
        public Nullable<byte> DUREE_1 { get; set; }
        public Nullable<byte> DUREE_2 { get; set; }
        public Nullable<byte> DUREE_3 { get; set; }
    }
}
