//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_PARAMETRES
    {
        public string COD_PARAM { get; set; }
        public string VAL_PARAM { get; set; }
        public Nullable<System.DateTime> DAT_PARAM { get; set; }
        public string OBSERV { get; set; }
        public string COD_S_ORD { get; set; }
    }
}
