//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CONSIDERANTS
    {
        public short COD_CONSID { get; set; }
        public string LIB_CONSID { get; set; }
        public string TYPE_CONSID { get; set; }
        public string LIB_CONSID_A { get; set; }
    }
}
