//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_AG_PROMO
    {
        public int COD_AG { get; set; }
        public Nullable<int> NUM_ID { get; set; }
        public string ANNEE_LOI { get; set; }
        public string NUM_LOI { get; set; }
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public string COD_DEP { get; set; }
        public string COD_ART { get; set; }
        public string COD_SRV { get; set; }
        public string COD_S_AF { get; set; }
        public Nullable<byte> COD_ECH { get; set; }
        public Nullable<System.DateTime> A_ANC_ELO { get; set; }
        public Nullable<byte> A_COD_ELO { get; set; }
        public Nullable<System.DateTime> N_ANC_ELO { get; set; }
        public Nullable<byte> N_COD_ELO { get; set; }
        public Nullable<short> NOTE { get; set; }
        public Nullable<System.DateTime> ANC_ADM { get; set; }
        public Nullable<short> N_INDICE { get; set; }
        public string CIN_A_AG { get; set; }
        public Nullable<int> CIN_N_AG { get; set; }
        public Nullable<short> NOTE_AG { get; set; }
        public Nullable<short> A_INDICE { get; set; }
        public Nullable<short> COD_LOC { get; set; }
        public Nullable<int> NUMCAP { get; set; }
        public Nullable<decimal> IMP_BUDG { get; set; }
        public string COD_S_ORD { get; set; }
    }
}
