//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_SS_TYP_MVT
    {
        public string TYP_MVT { get; set; }
        public short SS_TYP_MVT { get; set; }
        public string COD_POS { get; set; }
        public string LIB_SS_TYP_MVT { get; set; }
        public string LIB_ABREGE { get; set; }
        public Nullable<short> TYP_INT { get; set; }
        public Nullable<short> TYP_POS { get; set; }
        public string LIB_SS_TYP_MVT_A { get; set; }
    }
}
