//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ART_OLD
    {
        public string COD_DEP { get; set; }
        public string COD_ART { get; set; }
        public string LIB_ART { get; set; }
        public string LIB_ART_A { get; set; }
    }
}
