//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_IMP_BUD
    {
        public Nullable<decimal> IMP_BUD { get; set; }
        public string COD_DEP { get; set; }
        public string COD_ART { get; set; }
        public string COD_SRV { get; set; }
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public string COD_S_ST { get; set; }
        public int ID_IMP_BUD { get; set; }
    }
}
