//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_E_E_I_D
    {
        public short COD_ECH { get; set; }
        public short COD_ELO { get; set; }
        public Nullable<short> INDICE { get; set; }
        public Nullable<short> DUREE_1 { get; set; }
        public Nullable<short> DUREE_2 { get; set; }
        public Nullable<short> DUREE_3 { get; set; }
    }
}
