//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_TYP_MVT_LC
    {
        public string TYP_MVT_LC { get; set; }
        public string LIB_MVT_LC { get; set; }
        public string TYP_MVT_LC_BUD { get; set; }
        public string TYP_MVT_INTERNE { get; set; }
        public string REGULARISATION { get; set; }
        public string TYP_MENTION { get; set; }
    }
}
