//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_GRADE
    {
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public Nullable<short> COD_ECH { get; set; }
        public string LIB_GRADE { get; set; }
        public string LIB_GRADE_A { get; set; }
    }
}
