//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_SAF_FTF
    {
        public string COD_S_AF_FTF { get; set; }
        public string LIB_S_AF_FTF { get; set; }
        public string LIB_S_AF_FTF_A { get; set; }
    }
}
