//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ANIMATEUR
    {
        public string COD_ANIMATEUR { get; set; }
        public string COD_SPE { get; set; }
        public string NOM_PR_ANIMATEUR { get; set; }
        public string ORIGINE_ANIMATEUR { get; set; }
        public string TELEPHONE { get; set; }
        public string ADRESSE { get; set; }
        public string NOM_PR_ANIMATEUR_ARAB { get; set; }
        public string ADRESSE_ARAB { get; set; }
        public Nullable<int> COD_AG { get; set; }
    }
}
