//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_G_E_I_D_OLD
    {
        public byte COD_ELO { get; set; }
        public string COD_CATEG { get; set; }
        public string COD_CORPS { get; set; }
        public string COD_CADRE { get; set; }
        public string COD_GRADE { get; set; }
        public Nullable<short> INDICE { get; set; }
        public Nullable<byte> DUREE_1 { get; set; }
        public Nullable<byte> DUREE_2 { get; set; }
        public Nullable<byte> DUREE_3 { get; set; }
        public Nullable<byte> DUREE_4 { get; set; }
        public Nullable<byte> DUREE_5 { get; set; }
        public Nullable<byte> DUREE_6 { get; set; }
        public Nullable<byte> DUREE_7 { get; set; }
        public Nullable<byte> DUREE_8 { get; set; }
        public Nullable<byte> DUREE_9 { get; set; }
        public Nullable<byte> DUREE_10 { get; set; }
    }
}
