//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_AGENT_PB
    {
        public int NUM_PB { get; set; }
        public int COD_AG { get; set; }
        public System.DateTime DAT_SIT_PB { get; set; }
        public Nullable<System.DateTime> DAT_FIN { get; set; }
        public Nullable<byte> NB_OCC { get; set; }
        public Nullable<byte> NB_LIB { get; set; }
        public Nullable<int> MVT_LIB { get; set; }
        public Nullable<int> MVT_OCC { get; set; }
    }
}
