//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_VIS_CHAMPS_FORM
    {
        public string TYP_MVT { get; set; }
        public string LIB_CHAMPS { get; set; }
        public short ORDRE { get; set; }
        public Nullable<short> SS_TYP_MVT { get; set; }
        public short PAGE { get; set; }
        public Nullable<short> POSX { get; set; }
        public Nullable<short> POSY { get; set; }
        public Nullable<short> LARGEUR { get; set; }
        public Nullable<short> ACTIVER { get; set; }
        public short CACHER { get; set; }
        public string INVITE { get; set; }
        public Nullable<short> LIB_POSX { get; set; }
        public Nullable<short> LIB_POSY { get; set; }
        public Nullable<short> LIB_LARGEUR { get; set; }
        public Nullable<short> ORDRE_TABULATION { get; set; }
    }
}
