//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANCHES_REFERENCES
    {
        public string COD_S_ORD { get; set; }
        public int DEBUT { get; set; }
        public int FIN { get; set; }
        public int COURANT { get; set; }
    }
}
