//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        public short COD_USR { get; set; }
        public string LIB_USR { get; set; }
        public Nullable<System.DateTime> DAT_CREAT { get; set; }
        public Nullable<System.DateTime> DAT_ACCES { get; set; }
        public string MOT_DE_PASSE { get; set; }
        public string MOT_DE_PASSE_BASE { get; set; }
        public string COD_S_ORD { get; set; }
        public string PRINTER_NAME { get; set; }
        public string PRINTER_TYPE { get; set; }
    }
}
