//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIS_CHAMPS_FORM
    {
        public string TYP_MVT { get; set; }
        public string LIB_CHAMPS { get; set; }
        public byte ORDRE { get; set; }
        public Nullable<byte> SS_TYP_MVT { get; set; }
        public bool PAGE { get; set; }
        public Nullable<byte> POSX { get; set; }
        public Nullable<byte> POSY { get; set; }
        public Nullable<byte> LARGEUR { get; set; }
        public Nullable<bool> ACTIVER { get; set; }
        public bool CACHER { get; set; }
        public string INVITE { get; set; }
        public Nullable<byte> LIB_POSX { get; set; }
        public Nullable<byte> LIB_POSY { get; set; }
        public Nullable<byte> LIB_LARGEUR { get; set; }
        public Nullable<byte> ORDRE_TABULATION { get; set; }
    }
}
