//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma.metl.sirh.Model.Ora
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZLOG_TAB_SAF_OLD
    {
        public decimal ZID_SEQ { get; set; }
        public string COD_S_AF { get; set; }
        public Nullable<System.DateTime> ZDATE_OPERATION { get; set; }
        public string ZOPERATION { get; set; }
        public string ZSTATUT_OPER { get; set; }
        public string ZUTILISATEUR { get; set; }
        public string ZIP_ADRESSE { get; set; }
        public string ZXMLOLDDATA { get; set; }
        public string ZXMLNEWDATA { get; set; }
    }
}
